# 开发环境快速启动配置
# 使用: docker-compose -f docker-compose.dev.yml up -d

version: '3.8'

services:
  # 只启动核心服务
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION:-15}
    image: ${POSTGRES_IMAGE_NAME:-custom-postgres}:dev
    container_name: ${COMPOSE_PROJECT_NAME:-pg-custom}-postgres-dev
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_secure_password_123}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ${BACKUP_PATH:-./backups}:/backups
      - ./scripts:/docker-entrypoint-initdb.d:ro

    networks:
      - pg_dev_network

volumes:
  postgres_dev_data:
    driver: local

networks:
  pg_dev_network:
    driver: bridge
